### ISSUE TITLE
7.4.X CreateListReverseIterator ( list ) "ascending"? 

### ISSUE THREAD

**Issue by rwaldron** [leebyron/ecmascript-reverse-iterator#1]
https://github.com/leebyron/ecmascript-reverse-iterator#74x--createlistreverseiterator--list-

> The abstract operation CreateListReverseIterator with argument list creates an Iterator (25.1.1.2) object whose next method returns the successive elements of list in **ascending** (reverse) order. It performs the following steps:

This should read **descending**

**Comment by leebyron** [comment]
Thanks. Good catch
